# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            IamEld3st
tagline:          'Weeb developer'
description:      'A website where I do stuff'
url:              http://iameld3st.xyz
baseurl:          /

author:
  name:           'IamEld3st'
  url:            http://iameld3st.xyz

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/IamEld3st/iameld3st.github.io
