# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Blog
tagline:          'Sofware engineer blog'
description:      'A website where I do stuff'
url:              http://iameld3st.github.io
baseurl:          /

author:
  name:           'Andrzej Szczepaniak'
  url:            http://iameld3st.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/IamEld3st/iameld3st.github.io
